### PR TITLE
Add icon

### LINKED ISSUE #5: Add icon to repo and store page

### PR DESCRIPTION
**Pull request by hootio**
Closes #5

### CODE REVIEW

**Review by supervanya — COMMENTED** [review]
looks like the icon has a white background, it would be cool if it was transparent so it can blend with whatever vscode background is set, otherwise it is bleeding my eyes out in dark mode :D 

I can try to find original and re-export it.

image

**Comment by supervanya** [comment]
should we merge this one and open a different one once we have a new logo or keep this one open until we get a new logo (i am talking about mouse in the mouse trap)

**Comment by hootio** [comment]
> should we merge this one and open a different one once we have a new logo or keep this one open until we get a new logo (i am talking about mouse in the mouse trap)

Yeah we can merge this and then do the new one later. I won't close the issue then

**Comment by supervanya** [comment]
@hootio I added new logo and pushed a commit to your branch. We can merge it now!

**Review by supervanya — APPROVED** [review]

**Pull request merged**
